[package]
name = "frameworks"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "pm3"
path = "src/main.rs"

[dependencies]
adapters = { path = "../adapters" }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
