[package]
name = "usecases"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
entities = { path = "../entities" }
futures-util = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ctor = { workspace = true }
test_trace = { path = "../test_trace" }
tokio = { workspace = true }
